sudo: false
language: python
python:
- 3.6.9
- 3.7.9
- 3.8.5
before_install:
- pip install poetry
install:
- poetry install
script:
- make lint
- make docs
- make test
after_success:
- poetry run codecov
